export const arrOfOrders = [
  {
    id: "1234dfs141",
    userName: "Eren Jeager",
    img: "src/profile-picture.png",
    orderName: "Spicy seasoned noodles ",
    price: "$45",
    status: "completed",
  },
  {
    id: "12sf341",
    userName: "Hangi Zoe",
    img: "src/profile-picture.png",
    orderName: "Beef sote",
    price: "$125",
    status: "pending",
  },
  {
    id: "32134141",
    userName: "Levi",
    img: "src/profile-picture.png",
    orderName: "Soup",
    price: "$12",
    status: "preparing",
  },
  {
    id: "123as434ff141",
    userName: "Joe",
    img: "src/profile-picture.png",
    orderName: "Ramen Noodle",
    price: "$25",
    status: "completed",
  },
  {
    id: "1234rfgadsv141",
    userName: "Krautz",
    img: "src/profile-picture.png",
    orderName: "Sezar Salade",
    price: "$8",
    status: "pending",
  },
  {
    id: "1234s34f141",
    userName: "Mike",
    img: "src/profile-picture.png",
    orderName: "Tofu",
    price: "$18",
    status: "preparing",
  },
  {
    id: "12343gdfs4ff141",
    userName: "Jeager",
    img: "src/profile-picture.png",
    orderName: "Seafood noodles ",
    price: "$225",
    status: "completed",
  },
  {
    id: "1234rfgsvfsdf141",
    userName: "Hangi",
    img: "src/profile-picture.png",
    orderName: "Raw meat",
    price: "$205",
    status: "pending",
  },
  {
    id: "123434ff1sags41",
    userName: "Eren",
    img: "src/profile-picture.png",
    orderName: "Kobe noodles ",
    price: "$95",
    status: "completed",
  },
  {
    id: "1234rgsfdffgsv141",
    userName: "Hangi",
    img: "src/profile-picture.png",
    orderName: "Fruit salad",
    price: "$25",
    status: "pending",
  },
];

export default {
  arrOfOrders,
};
