export const arrOfOrders = [
  {
    id: "1234dfs141",
    userName: "Eren Jeager",
    img: "src/profile-picture.png",
    orderName: "Spicy seasoned seafood noodles ",
    price: "$125",
    status: "completed",
  },
  {
    id: "12sf341",
    userName: "Hangi",
    img: "src/profile-picture.png",
    orderName: "Raw meat",
    price: "$12532",
    status: "pending",
  },
  {
    id: "32134141",
    userName: "Levi",
    img: "src/profile-picture.png",
    orderName: "Potato",
    price: "$32",
    status: "preparing",
  },
  {
    id: "123as434ff141",
    userName: "Eren Jeager",
    img: "src/profile-picture.png",
    orderName: "Spicy seasoned seafood noodles ",
    price: "$125",
    status: "completed",
  },
  {
    id: "1234rfgadsv141",
    userName: "Hangi",
    img: "src/profile-picture.png",
    orderName: "Raw meat",
    price: "$12532",
    status: "pending",
  },
  {
    id: "1234s34f141",
    userName: "Levi",
    img: "src/profile-picture.png",
    orderName: "Potato",
    price: "$32",
    status: "preparing",
  },
  {
    id: "12343gdfs4ff141",
    userName: "Eren Jeager",
    img: "src/profile-picture.png",
    orderName: "Spicy seasoned seafood noodles ",
    price: "$125",
    status: "completed",
  },
  {
    id: "1234rfgsvfsdf141",
    userName: "Hangi",
    img: "src/profile-picture.png",
    orderName: "Raw meat",
    price: "$12532",
    status: "pending",
  },
  {
    id: "123434ff1sags41",
    userName: "Eren Jeager",
    img: "src/profile-picture.png",
    orderName: "Spicy seasoned seafood noodles ",
    price: "$125",
    status: "completed",
  },
  {
    id: "1234rgsfdffgsv141",
    userName: "Hangi",
    img: "src/profile-picture.png",
    orderName: "Raw meat",
    price: "$12532",
    status: "pending",
  },
];

export default {
  arrOfOrders,
};
